services:
    postgres:
        image: postgres
        container_name: postgres
        restart: always

        ports:
            - "5432:5432"

        env_file:
            - ./.env

        environment :
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: sensors

        volumes:
            - /var/db/postgres/sensors

    redis:
        image: redis
        container_name: redis
        restart: always

        depends_on:
            - postgres

        ports:
            - "6379:6379"

        volumes:
            - /var/db/postgres/redis

volumes:
    postgres:
        name: db