-- AlterTable
ALTER TABLE "Sensor" ALTER COLUMN "frequency" SET DEFAULT 5000,
ALTER COLUMN "transparency" SET DEFAULT 100,
ALTER COLUMN "temperature" SET DEFAULT 20,
ALTER COLUMN "x" SET DEFAULT 0,
ALTER COLUMN "y" SET DEFAULT 0,
ALTER COLUMN "z" SET DEFAULT 0;
